# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/xdc.xdc

# Block Designs: bd/hw/hw.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw || ORIG_REF_NAME==hw} -quiet] -quiet

# IP: bd/hw/ip/hw_processing_system7_0_0/hw_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_processing_system7_0_0 || ORIG_REF_NAME==hw_processing_system7_0_0} -quiet] -quiet

# XDC: bd/hw/hw_ooc.xdc
